export const extensionImage = [
  'jpg',
  'jpeg',
  'png',
  'gif',
  'bmp',
  'tiff',
  'tif',
  'svg',
  'webp',
  'heic',
  'raw',
  'psd',
  'ai',
  'eps',
  'ico',
  'jfif',
  'pgm',
  'ppm',
  'tga',
  'dds',
  'exr',
  'hdr'
]

export const extensionVideo = [
  'mp4',
  'avi',
  'mkv',
  'mov',
  'wmv',
  'flv',
  'webm',
  'mpg',
  'mpeg',
  'm4v',
  '3gp',
  'mxf',
  'ogv',
  'vob',
  'ts',
  'rm',
  'rmvb'
]

export const optionColumnExportAccount = [
  { header: 'UID', key: 'uid' },
  { header: 'Mật khẩu', key: 'password' },
  { header: '2FA', key: '_2fa' },
  { header: 'Email', key: 'email' },
  { header: 'Mật khẩu email', key: 'pass_email' },
  { header: 'Proxy', key: 'proxy' },
  { header: 'Mail khôi phục', key: 'recovery_email' },
  { header: 'Mật khẩu mail khôi phục', key: 'pass_recovery_email' },
  { header: 'Token', key: 'token' },
  { header: 'Cookie', key: 'cookie' },
  { header: 'Tên', key: 'name' },
  { header: 'Ảnh đại diện', key: 'avatar' },
  { header: 'Ảnh bìa', key: 'cover' },
  { header: 'Sinh nhật', key: 'birthday' },
  { header: 'Giới tính', key: 'gender' },
  { header: 'Số điện thoại', key: 'phone_number' },
  { header: 'Địa chỉ', key: 'address' },
  { header: 'Ngày tạo', key: 'created_time' },
  { header: 'Số lượng bạn bè', key: 'friend_count' },
  { header: 'Số lượng page', key: 'page_profile_count' },
  { header: 'Số lượng nhóm', key: 'group_count' },
  { header: 'Số nhóm làm admin', key: 'admin_group_count' },
  { header: 'Trạng thái', key: 'status' },
  { header: 'Note', key: 'note' },
  { header: 'Hành động cuối', key: 'last_action' },
  { header: 'Thời gian hành động cuối', key: 'last_time_action' },
  { header: 'Trạng thái checkpoint', key: 'checkpoint_state' }
]

export const optionColumnExportPost = [
  { header: 'Tiêu đề', key: 'title' },
  { header: 'Nội dung', key: 'content' },
  { header: 'Hình ảnh', key: 'picture' },
  { header: 'Số lượng ảnh', key: 'numpicture' },
  { header: 'Kiểu bài viết', key: 'type_post' }
]

export const optionColumnExportGMap = [
  { header: 'Từ khoá', key: 'keyword' },
  { header: 'Tên cửa hàng', key: 'store_name' },
  { header: 'Số điện thoại', key: 'phone' },
  { header: 'Website', key: 'website' },
  { header: 'Đánh giá, số lượng đánh giá', key: 'rating' },
  { header: 'Địa chỉ', key: 'address' },
  { header: 'Thời gian mở cửa', key: 'open_time' },
  { header: 'Ảnh đại diện', key: 'avatar' },
  { header: 'Tạo độ GPS', key: 'gps' }
]

export const optionHeaderCsvFile = [
  'uid',
  'password',
  '_2fa',
  'email',
  'pass_email',
  'recovery_email',
  'pass_recovery_email',
  'token',
  'cookie',
  'name',
  'avatar',
  'cover',
  'birthday',
  'gender',
  'phone_number',
  'address',
  'created_time',
  'friend_count',
  'page_profile_count',
  'group_count',
  'admin_group_count',
  'status',
  'note',
  'last_action',
  'last_time_action',
  'checkpoint_state'
]

export const optionHeaderRowCsvFile = [
  {
    uid: 'UID',
    password: 'Mật khẩu',
    _2fa: '2FA',
    email: 'Email',
    pass_email: 'Mật khẩu email',
    proxy: 'Proxy',
    recovery_email: 'Mail khôi phục',
    pass_recovery_email: 'Mật khẩu mail khôi phục',
    token: 'Token',
    cookie: 'Cookie',
    name: 'Tên',
    avatar: 'Ảnh đại diện',
    cover: 'Ảnh bìa',
    birthday: 'Sinh nhật',
    gender: 'Giới tính',
    phone_number: 'Số điện thoại',
    address: 'Địa chỉ',
    created_time: 'Ngày tạo',
    friend_count: 'Số lượng bạn bè',
    page_profile_count: 'Số lượng page',
    group_count: 'Số lượng nhóm',
    admin_group_count: 'Số nhóm làm admin',
    status: 'Trạng thái',
    note: 'Note',
    last_action: 'Hành động cuối',
    last_time_action: 'Thời gian hành động cuối',
    checkpoint_state: 'Trạng thái checkpoint'
  }
]
